{{- if .external_tools -}} # external_tools
[".local/bin/kubectl"]
  type = "file"
  refreshPeriod = "168h"
  url = "https://dl.k8s.io/release/v{{ .tools.kubectl.version }}/bin/{{ .chezmoi.os }}/{{ .chezmoi.arch }}/kubectl"
  executable = true
[".local/bin/kubectl-oidc_login"]
  type = "archive-file"
  refreshPeriod = "168h"
  url = '{{ gitHubLatestReleaseAssetURL "int128/kubelogin" (printf "kubelogin_%s_%s.zip" .chezmoi.os .chezmoi.arch) }}'
  executable = true
  path = "kubelogin"
[".local/bin/kubectl-krew"]
  type = "archive-file"
  executable = true
  refreshPeriod = "168h"
  url = '{{ gitHubLatestReleaseAssetURL "kubernetes-sigs/krew" (printf "krew-%s_%s.tar.gz" .chezmoi.os .chezmoi.arch) }}'
  path = "./krew-{{ .chezmoi.os }}_{{ .chezmoi.arch }}"
[".local/bin/k3d"]
  type = "file"
  refreshPeriod = "168h"
  url = '{{ gitHubLatestReleaseAssetURL "k3d-io/k3d" (printf "k3d-%s-%s*" .chezmoi.os .chezmoi.arch) }}'
  executable = true
[".local/bin/kind"]
  type = "file"
  refreshPeriod = "168h"
  url = '{{ gitHubLatestReleaseAssetURL "kubernetes-sigs/kind" (printf "kind-%s-%s*" .chezmoi.os .chezmoi.arch) }}'
  executable = true
[".local/bin/age"]
  type = "archive-file"
  refreshPeriod = "168h"
  url = "https://github.com/FiloSottile/age/releases/download/v{{ .tools.age.version }}/age-v{{ .tools.age.version }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
  path = "age/age"
  executable = true
[".local/bin/gopass"]
  type = "archive-file"
  refreshPeriod = "168h"
  url = '{{ gitHubLatestReleaseAssetURL "gopasspw/gopass" (printf "gopass-*-%s-%s.tar.gz" .chezmoi.os .chezmoi.arch ) }}'
  path = "gopass"
  executable = true
[".local/bin/sops"]
  type = "file"
  refreshPeriod = "168h"
  url = '{{ gitHubLatestReleaseAssetURL "getsops/sops" (printf "sops-*.%s.%s*" .chezmoi.os .chezmoi.arch ) }}'
  executable = true
[".local/bin/yq"]
  type = "file"
  refreshPeriod = "168h"
  url = '{{ gitHubLatestReleaseAssetURL "mikefarah/yq" (printf "yq_%s_%s*" .chezmoi.os .chezmoi.arch ) }}'
  executable = true
[".local/bin/helm"]
  type = "archive-file"
  refreshPeriod = "168h"
  url = "https://get.helm.sh/helm-v{{ .tools.helm.version }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
  executable = true
  path = "{{ .chezmoi.os }}-{{ .chezmoi.arch }}/helm"
[".local/bin/flux"]
  type = "archive-file"
  refreshPeriod = "168h"
  url = '{{ gitHubLatestReleaseAssetURL "fluxcd/flux2" (printf "flux_*_%s_%s.tar.gz" .chezmoi.os .chezmoi.arch) }}'
  path = "flux"
  executable = true
[".local/bin/fzf"]
  type = "archive-file"
  executable = true
  refreshPeriod = "168h"
  url = '{{ gitHubLatestReleaseAssetURL "junegunn/fzf" (printf "*%s_%s*" .chezmoi.os .chezmoi.arch) }}'
  path = "fzf"
[".local/go"]
  type = "archive"
  refreshPeriod = "168h"
  url = "https://go.dev/dl/go{{ .tools.go.version }}.{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
  exact = false
  stripComponents = 1
{{ end -}} # external_tools
