[tools.bw]
    version = "2025.3.0"
[tools.bws]
    version = "1.0.0"
[tools.kubectl]
    version = "1.35.0"
[tools.cloudflared]
    version = "2025.9.1"
[tools.go_task]
    version = "3.41.0"
[tools.vagrant]
    version = "2.4.5"
[tools.rclone]
    version = "1.70.2"
[tools.kopia]
    version = "0.22.3"
[tools.helm]
    version = "3.19.5"
[tools.linkerd2]
    version = "25.1.2"
[tools.terraform]
    version = "1.14.3"
[tools.go]
    version = "1.25.5"
