[tools]
awscli = { version = "2", symlink_bins = "true" }
node = "24"
"npm:@slidev/cli" = "latest"
python = "3.14"
usage = "latest"
# yt-dlp = "latest"

[settings]
experimental = true

[env]
_MISE_ENV_VAR = "mise"
